<?php
/** @var \Doroshko\WishReward\ViewModel\WishContentViewModel $viewModel **/

$viewModel = $block->getViewModel();
?>

<?php if ($viewModel->canShowForm()): ?>
    <?= $block->getChildHtml("wishreward.canvas") ?>

    <div id="wish-form-container" class="<?= !$viewModel->isWheelEnabled() ? 'wheel-disabled' : '' ?>">
        <div class="wish-content-container">
            <?= $block->getChildHtml("wishreward.form") ?>
            <?= $block->getChildHtml("wishreward.wheel") ?>
        </div>

        <?= $block->getChildHtml("wishreward.coupon") ?>
    </div>

    <script type="text/x-magento-init">
        {
            "#wish-form-container": {
                "Doroshko_WishReward/js/form-handler": {
                    "ajaxUrl": "<?= $this->escapeUrl($viewModel->getFormActionUrl()) ?>",
                    "wheelSectors": <?= json_encode($viewModel->getWheelSectors()) ?>,
                    "rotationDuration": <?= json_encode($viewModel->getRotationDuration()) ?>,
                    "showWheel": <?= json_encode($viewModel->isWheelEnabled()) ?>
                }
            }
        }
    </script>
<?php else: ?>
    <?= $block->getChildHtml("wishreward.login") ?>
<?php endif; ?>