<?php
/**
 * @var $block \Magento\Backend\Block\Template
 * @var $escaper \Magento\Framework\Escaper
 */
?>

<div class="wish-popup minimized" id="wish-container">
    <div class="cta-wish-content">
        <div class="cta-wish-content-image"></div>
        <div class="cta-wish-content-info">
            <p><?= $block->escapeHtml(__('Share your New Year wish and unlock a special discount!')); ?></p>

            <div id="button-container">
                <button class="the-primary-button wish-button" id="open-wish-modal">
                    <span class="button-text"><?= $block->escapeHtml(__('Make a Wish')); ?></span>
                    <span class="round" />
                </button>
            </div>
        </div>
    </div>
    
    <div class="main-wish-content"></div>
</div>

<script type="text/x-magento-init">
{
    "#wish-container": {
        "Doroshko_WishReward/js/cta": {
            "ajaxUrl": "<?= $block->getUrl('wishreward/ajax/loadtemplate') ?>"
        }
    }
}
</script>