<?php
/**
 * @var $block \Magento\Backend\Block\Template
 * @var $escaper \Magento\Framework\Escaper
 */
?>

<div class="cta-wish-container" id="cta-wish-container">
    <div class="cta-wish-content">
        <h1><?= $block->escapeHtml(__('Write a New Year wish')); ?></h1>
        <p><?= $block->escapeHtml(__('Share your wish and get an exclusive discount!')); ?></p>
        <button class="cta-wish-button" id="open-wish-modal">
            <?= $block->escapeHtml(__('Make a Wish')); ?>
        </button>
    </div>
</div>

<script type="text/x-magento-init">
{
    "#open-wish-modal": {
        "Doroshko_WishReward/js/cta": {
            "ajaxUrl": "<?= $block->getUrl('wishreward/ajax/loadtemplate') ?>"
        }
    }
}
</script>

<style>
    /* Контейнер для CTA */
.cta-wish-container {
    background: linear-gradient(135deg, #ff9a9e, #fad0c4); /* Градиентный фон */
    padding: 20px 15px;
    text-align: center;
    border-radius: 15px; /* Скругленные углы */
    box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2); /* Тень */
    max-width: 400px;
    margin: 40px auto; /* Центрирование */
    position: fixed;
    bottom: 30px;
    right: 40px;
    z-index: 99;
}

/* Заголовок CTA */
.cta-wish-content h1 {
    font-size: 2rem;
    color: #ffffff;
    margin-bottom: 10px;
    font-weight: bold;
    text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3); /* Тень текста */
}

/* Текст CTA */
.cta-wish-content p {
    font-size: 1.2rem;
    color: #ffffff;
    margin-bottom: 20px;
    line-height: 1.5;
    text-shadow: 1px 1px 3px rgba(0, 0, 0, 0.2); /* Тень текста */
}

/* Кнопка */
.cta-wish-button {
    background-color: #ffffff;

    color: #ff6f61;
    border: none;
    padding: 15px 30px;
    font-size: 1rem;
    font-weight: bold;
    border-radius: 50px; /* Скругленные края кнопки */
    cursor: pointer;
    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2); /* Тень кнопки */
    transition: all 0.3s ease; /* Анимация наведения */
}

.cta-wish-button:hover {
    background-color: #ff6f61;
    color: #ffffff;
    transform: translateY(-5px); /* Поднимаем кнопку */
    box-shadow: 0 6px 15px rgba(0, 0, 0, 0.3); /* Увеличиваем тень */
}

</style>