<?php
/**
 * @var $block \Magento\Backend\Block\Template
 * @var $escaper \Magento\Framework\Escaper
 */
?>

<div class="wish-cta" id="wish-container">
    <div class="wish-cta-image"></div>
    <div class="wish-cta-content">
        <h3 class="wish-cta-title"><?= $block->escapeHtml(__('Share your Christmas wish and unlock a special discount!')); ?></h3>

        <button class="wish-cta-btn" id="open-wish-modal">
            <span><?= $block->escapeHtml(__('Make a Wish')); ?></span>
        </button>
    </div>
    <!-- <button class="wish-cta-close"></button> -->
</div>

<script type="text/x-magento-init">
{
    "#wish-container": {
        "Doroshko_WishReward/js/cta": {
            "ajaxUrl": "<?= $block->getUrl('wishreward/ajax/loadtemplate') ?>"
        }
    }
}
</script>